### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by 0xR** [paularmstrong/mocha-to-jest-codemod#1]
Steps I took:
1. Clone the project
2. install jscodemod
3. run on my tests, nothing happens
4. try again on an empty project
3. run the command: `jscodeshift file.js -t ../mocha-to-jest-codemod/chai-assert-to-expect.js`

got this output:
```
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
All done.
Results:
0 errors
1 unmodified
0 skipped
0 ok
Time elapsed: 0.791seconds
```

file.js:
```js
    expect(window.document.body.className).to.equal('');
```

**Comment by paularmstrong** [comment]
This is for chai `assert`, not `expect`. You'll need to write your own codemod for *chai expect to jest expect*.

**Comment by 0xR** [comment]
Ah that explains a lot. Maybe you can put this more clearly in the README.
